providers = ["php"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs --no-interaction",
    "npm install"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "php artisan storage:link && php artisan migrate --force && php -S 0.0.0.0:$PORT -t public"